#!/usr/bin/env python3
"""
Blocklist Comparison Script
Compares firehol sources against your active pfBlockerNG lists
and produces recommendations.json
"""

import json
import os
from datetime import datetime, timezone

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from netutil import CoverageIndex, is_excluded, is_geoip_url, is_self_url, parse_ips

HEADERS = {"User-Agent": "blocklist-manager/1.0"}
TIMEOUT = 30

COMPARE_SOURCES = {
    "firehol_level1": {
        "url": "https://raw.githubusercontent.com/ktsaou/blocklist-ipsets/master/firehol_level1.netset",
        "description": "FireHOL Level 1 – top consensus blocklist aggregating 10+ trusted sources",
        "type": "ip"
    },
    "firehol_level2": {
        "url": "https://raw.githubusercontent.com/ktsaou/blocklist-ipsets/master/firehol_level2.netset",
        "description": "FireHOL Level 2 – broader coverage, more aggressive blocking",
        "type": "ip"
    },
    "blocklist_de_all": {
        "url": "https://lists.blocklist.de/lists/all.txt",
        "description": "Blocklist.de – IPs that attacked SSH, FTP, web servers in last 48h",
        "type": "ip"
    }
}

MY_LISTS_FILE = "my_lists.json"
OUTPUT_FILE   = "output/recommendations.json"
CACHE_FILE    = "cache/ip_source_cache.json"


def make_session():
    retry = Retry(
        total=3,
        backoff_factor=2,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=("GET",),
    )
    session = requests.Session()
    session.mount("https://", HTTPAdapter(max_retries=retry))
    session.mount("http://", HTTPAdapter(max_retries=retry))
    return session


SESSION = make_session()


def download(url, label):
    print(f"  Downloading: {label}")
    try:
        r = SESSION.get(url, headers=HEADERS, timeout=TIMEOUT)
        r.raise_for_status()
        return r.text
    except Exception as e:
        raise RuntimeError(f"Failed to download {label}: {e}")


def load_cache():
    if not os.path.exists(CACHE_FILE):
        return {}
    try:
        with open(CACHE_FILE) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def get_source_nets(url, label, cache_sources):
    # Reuse the exact snapshot merge.py downloaded moments ago in this same
    # run, instead of downloading again - a second independent download
    # drifts against fast-moving sources like firehol_level2 and never
    # settles at 0 gaps. Only fall back to a live download if merge.py
    # hasn't run yet or didn't cache this URL (e.g. run standalone).
    cached = cache_sources.get(url)
    if cached is not None:
        print(f"  Using cached snapshot: {label} ({len(cached)} entries)")
        nets, _ = parse_ips("\n".join(cached))
        return nets
    print(f"  No cache for {label}, downloading fresh...")
    nets, _ = parse_ips(download(url, label))
    return nets


def get_my_ip_nets(my_ip_urls, cache):
    # Same reasoning as get_source_nets: reuse merge.py's exact base-list
    # snapshot instead of re-downloading. Spamhaus/Emerging Threats/etc.
    # churn constantly, so an independent re-download minutes later drifts
    # from what merge.py actually used to compute merged_ip.txt.
    cached = cache.get("my_ip_nets")
    if cached is not None:
        print(f"  Using cached base-list snapshot ({len(cached)} networks)")
        nets, _ = parse_ips("\n".join(cached))
        return nets
    print("  No cached base-list snapshot, downloading fresh...")
    nets = set()
    for url in my_ip_urls:
        parsed, _ = parse_ips(download(url, url.split("/")[-1]))
        nets.update(parsed)
        print(f"     {url.split('/')[-1]}: {len(parsed)} networks")
    return nets


def main():
    print("=== Blocklist Comparison ===")
    print(f"Time: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")

    print("\n[1] Loading my pfBlockerNG lists...")
    with open(MY_LISTS_FILE) as f:
        my_lists = json.load(f)

    # Exclude GeoIP and blocklist-manager URLs from download.
    # GeoIP is irrelevant for coverage; merged_ip.txt is added from local disk below.
    my_ip_urls = [u for u in my_lists.get("ip_lists", []) if not is_geoip_url(u) and not is_self_url(u)]
    print(f"  My IP sources: {len(my_ip_urls)}")

    print("\n[2] Loading my IP lists...")
    cache = load_cache()
    my_nets = get_my_ip_nets(my_ip_urls, cache)

    # Add merged_ip.txt from local disk (already generated by merge.py in this same run).
    # This ensures coverage calculation includes gaps already filled, without
    # downloading a stale version from GitHub.
    merged_ip_path = "output/merged_ip.txt"
    if os.path.exists(merged_ip_path):
        with open(merged_ip_path) as f:
            merged_nets, _ = parse_ips(f.read())
        my_nets.update(merged_nets)
        print(f"     merged_ip.txt (local): {len(merged_nets)} networks")

    print(f"  Total my networks: {len(my_nets)}")
    my_index = CoverageIndex(my_nets)

    print("\n[3] Comparing against external sources...")
    cache_sources = cache.get("sources", {})
    recommendations = []

    for name, source in COMPARE_SOURCES.items():
        print(f"\n  Checking: {name}")
        source_nets = get_source_nets(source["url"], name, cache_sources)
        if not source_nets:
            raise RuntimeError(f"{name}: no networks found - refusing to publish empty comparison")
        new_nets = [n for n in source_nets if not my_index.overlaps(n) and not is_excluded(n)]
        coverage_pct = round((1 - len(new_nets) / max(len(source_nets), 1)) * 100, 1)

        print(f"    Total networks in source: {len(source_nets)}")
        print(f"    New networks not covered: {len(new_nets)}")
        print(f"    Your coverage: {coverage_pct}%")

        recommendations.append({
            "name": name,
            "description": source["description"],
            "url": source["url"],
            "type": source["type"],
            "total_networks": len(source_nets),
            "new_networks": len(new_nets),
            "your_coverage_pct": coverage_pct,
            "worth_adding": len(new_nets) > 100
        })

    source_order = list(COMPARE_SOURCES.keys())
    recommendations.sort(key=lambda x: source_order.index(x["name"]))

    output = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "my_networks_count": len(my_nets),
        "recommendations": recommendations
    }

    os.makedirs("output", exist_ok=True)
    tmp = OUTPUT_FILE + ".tmp"
    with open(tmp, "w") as f:
        json.dump(output, f, indent=2)
    os.replace(tmp, OUTPUT_FILE)

    print("\n=== Done ===")
    for r in recommendations:
        status = "Worth adding" if r["worth_adding"] else "Already covered"
        print(f"  {r['name']}: {r['new_networks']:,} new networks – {status}")


if __name__ == "__main__":
    main()
