#!/usr/bin/env python3
"""
Blocklist Comparison Script
Compares firehol sources against your active pfBlockerNG lists
and produces recommendations.json
"""

import requests
import ipaddress
import json
import os
from datetime import datetime, timezone

HEADERS = {"User-Agent": "blocklist-manager/1.0"}
TIMEOUT = 30

COMPARE_SOURCES = {
    "firehol_level1": {
        "url": "https://raw.githubusercontent.com/ktsaou/blocklist-ipsets/master/firehol_level1.netset",
        "description": "FireHOL Level 1 – top consensus blocklist aggregating 10+ trusted sources",
        "type": "ip"
    },
    "firehol_level2": {
        "url": "https://raw.githubusercontent.com/ktsaou/blocklist-ipsets/master/firehol_level2.netset",
        "description": "FireHOL Level 2 – broader coverage, more aggressive blocking",
        "type": "ip"
    },
    "blocklist_de_all": {
        "url": "https://lists.blocklist.de/lists/all.txt",
        "description": "Blocklist.de – IPs that attacked SSH, FTP, web servers in last 48h",
        "type": "ip"
    }
}

MY_LISTS_FILE = "my_lists.json"
OUTPUT_FILE   = "output/recommendations.json"

BOGON_RANGES = [
    ipaddress.ip_network("10.0.0.0/8"),
    ipaddress.ip_network("172.16.0.0/12"),
    ipaddress.ip_network("192.168.0.0/16"),
    ipaddress.ip_network("127.0.0.0/8"),
    ipaddress.ip_network("169.254.0.0/16"),
    ipaddress.ip_network("0.0.0.0/8"),
    ipaddress.ip_network("100.64.0.0/10"),
]


def is_bogon(net):
    return any(net.overlaps(b) for b in BOGON_RANGES)


def parse_ips(text):
    nets = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        entry = line.split()[0]
        try:
            nets.add(ipaddress.ip_network(entry, strict=False))
        except ValueError:
            pass
    return nets


def download(url, label):
    print(f"  Downloading: {label}")
    try:
        r = requests.get(url, headers=HEADERS, timeout=TIMEOUT)
        r.raise_for_status()
        return r.text
    except Exception as e:
        print(f"  ERROR: {e}")
        return ""


def nets_overlap(net, existing_nets):
    for existing in existing_nets:
        if net.overlaps(existing):
            return True
    return False


def main():
    print("=== Blocklist Comparison ===")
    print(f"Time: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")

    print("\n[1] Loading my pfBlockerNG lists...")
    with open(MY_LISTS_FILE) as f:
        my_lists = json.load(f)

    # Exclude ipverse (GeoIP) and blocklist-manager URLs from download
    # GeoIP is irrelevant for coverage; merged_ip.txt will be added from local disk below
    my_ip_urls = [u for u in my_lists.get("ip_lists", []) if "ipverse" not in u and "blocklist-manager" not in u]
    print(f"  My IP sources: {len(my_ip_urls)}")

    print("\n[2] Downloading my IP lists...")
    my_nets = set()
    for url in my_ip_urls:
        text = download(url, url.split("/")[-1])
        nets = parse_ips(text)
        my_nets.update(nets)
        print(f"     {url.split('/')[-1]}: {len(nets)} networks")

    # Add merged_ip.txt from local disk (already generated by merge.py in this same run)
    # This ensures coverage calculation includes gaps already filled — without downloading
    # a stale version from GitHub
    merged_ip_path = "output/merged_ip.txt"
    if os.path.exists(merged_ip_path):
        with open(merged_ip_path) as f:
            merged_nets = parse_ips(f.read())
        my_nets.update(merged_nets)
        print(f"     merged_ip.txt (local): {len(merged_nets)} networks")

    print(f"  Total my networks: {len(my_nets)}")

    print("\n[3] Comparing against external sources...")
    recommendations = []

    for name, source in COMPARE_SOURCES.items():
        print(f"\n  Checking: {name}")
        text = download(source["url"], name)
        if not text:
            continue

        source_nets = parse_ips(text)
        new_nets = [n for n in source_nets if not nets_overlap(n, my_nets) and not is_bogon(n)]
        coverage_pct = round((1 - len(new_nets) / max(len(source_nets), 1)) * 100, 1)

        print(f"    Total networks in source: {len(source_nets)}")
        print(f"    New networks not covered: {len(new_nets)}")
        print(f"    Your coverage: {coverage_pct}%")

        recommendations.append({
            "name": name,
            "description": source["description"],
            "url": source["url"],
            "type": source["type"],
            "total_networks": len(source_nets),
            "new_networks": len(new_nets),
            "your_coverage_pct": coverage_pct,
            "worth_adding": len(new_nets) > 100
        })

    source_order = list(COMPARE_SOURCES.keys())
    recommendations.sort(key=lambda x: source_order.index(x["name"]))

    output = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "my_networks_count": len(my_nets),
        "recommendations": recommendations
    }

    os.makedirs("output", exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(output, f, indent=2)

    print(f"\n=== Done ===")
    for r in recommendations:
        status = "Worth adding" if r["worth_adding"] else "Already covered"
        print(f"  {r['name']}: {r['new_networks']:,} new networks – {status}")


if __name__ == "__main__":
    main()
